name: CD

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*' # Enforce Semantic Versioning

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@3.5
      with:
        cli: 1.10.3.943

    - name: Build Bundle
      run: make bundle

    - name: Archive Bundle (Branch Pushes)
      if: ${{ startsWith(github.ref, 'refs/heads') }}
      uses: actions/upload-artifact@v2
      with:
        name: lrs-admin-ui-artifact-${{ github.sha }}
        path: target/bundle/**

    - name: Compress Bundle
      if: ${{ startsWith(github.ref, 'refs/tags') }}
      run: | # Need to cd so that the zip file doesn't contain the parent dirs
        cd target/bundle
        zip -r ../../lrs-admin-ui.zip ./

    - name: Craft Draft Release (Tag Pushes)
      if: ${{ startsWith(github.ref, 'refs/tags') }}
      uses: softprops/action-gh-release@v1
      with:
        # Defaults:
        # name: [tag name]
        # tag_name: github.ref
        body: "## Release Notes\nTODO: Create great release notes!"
        draft: true
        files: lrs-admin-ui.zip
